all:
  hosts:
    node1:
      ansible_host: 192.168.0.11
      ansible_user: administrator
    node2:
      ansible_host: 192.168.0.12
      ansible_user: administrator
    node3:
      ansible_host: 192.168.0.13
      ansible_user: administrator